title: 'cv.marvinroman.me'
default_lang: en
author:
  name: 'Marvin Roman'
  email: marvinroman@protonmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'CV for Marvin Roman: DevOps, Developer, Server Administrator'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
